name: publish npm 

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: publish npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'

      - name: install dependencies
        run: |
          npm install

      # - name: lint
      #   run: |
      #     npm run lint --if-present

      - name: build
        run: |
          npm run build
        env:
          NODE_ENV: production

      - name: publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        
      # - uses: 8398a7/action-slack@v3
      #   with:
      #     status: custom
      #     fields: workflow,job,commit,repo,ref,author,took
      #     custom_payload: |
      #       {
      #         attachments: [{
      #           color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
      #           text: `Ch-api-client ${{ github.event.client_payload.message.tag }} publish ${{ job.status }} in ${process.env.AS_TOOK}`,
      #         }]
      #       }
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.NPM_PUBLISHED }}
      #     if: always() # Pick up events even if the job fails or is canceled.